version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - pip install --upgrade awscli
      - dotnet restore DotnetLambda.Api/DotnetLambda.Api.csproj
      - dotnet restore DotnetLambda.Api.Tests/DotnetLambda.Api.Tests.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output DotnetLambda.Api/DotnetLambda.Api.csproj
      - dotnet publish -c release -o ./test_output DotnetLambda.Api.Tests/DotnetLambda.Api.Tests.csproj
      - dotnet vstest DotnetLambda.Api.Tests/test_output/DotnetLambda.Api.Tests.dll
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged-template.yml
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - packaged-template.yml
    - template-configuration.json
# These files are not needed because sam generates the packaged-template.yml above and packages the artifacts.
#    - template.yml
#    - DotnetLambda.Api/build_output/**/*
#    - scripts/**/*
#    - appspec.yml
